// Static dropdown options. These came directly from the brief — edit
// freely here if the lists ever change; no database change needed.

export const REGIONS = [
  'ASSAM',
  'BIHAR & JHARKHAND',
  'CHENNAI',
  'DEL & UP WEST',
  'GUJARAT',
  'HYDERABAD',
  'KARNATAKA',
  'KERALA',
  'KOLKATA',
  'INDORE',
  'MUMBAI',
  'ORISSA',
  'PUNJAB',
  'PUNE',
  'RAJASTHAN',
  'UP EAST',
];

export const SO_HQ = [
  'Mumbai', 'Pune', 'Kolhapur', 'Sangli', 'Solapur', 'Aurangabad', 'Nasik',
  'Jalgaon', 'Ahmedabad', 'Baroda', 'Surat', 'Rajkot', 'Indore', 'Bhopal',
  'Gwalior', 'Ujjain', 'Raipur', 'Jabalpur', 'Nagpur', 'Akola', 'Kolkatta',
  'Midnapur', 'Barasat', 'Howrah', 'Serampore', 'Barrackpore',
  'Behrampur(WB)', 'Siliguri', 'Burdwan', 'Asansol', 'Malda', 'Guwahati',
  'Tezpur', 'Agartala', 'Silchar', 'Imphal', 'Patna', 'Muzzafarpur',
  'Ranchi', 'Dhanbad', 'Bhagalpur', 'Jamshedpur', 'Bhubaneshwar', 'Cuttack',
  'Behrampur', 'Delhi', 'Meerut', 'Dehradun', 'Ghaziabad', 'Lucknow',
  'Kanpur', 'Jhansi', 'Varanasi', 'Gorakhpur', 'Allahabad', 'Haldwani',
  'Bareilly', 'Agra', 'Jaipur', 'Kota', 'Jodhpur', 'Bikaner', 'Udaipur',
  'Chandigarh', 'Ambala', 'Gurgaon', 'Rohtak', 'Amritsar', 'Ludhiana',
  'Jalandhar', 'Srinagar', 'Patiala', 'Bangalore', 'Mangalore', 'Hubli',
  'Davangree', 'Chennai', 'Pondicherry', 'Coimbatore', 'Salem',
  'Tirunelveli', 'Madurai', 'Trichy', 'Cochin', 'Trivandrum', 'Kottayam',
  'Calicut', 'Kannur', 'Trichur', 'Palakkad', 'Hyderabad', 'Warangal',
  'Vijaywada', 'Rajahmundry', 'Vizag',
];

export const SO_NAMES = [
  'Nilesh Narendra Giri', 'Pradumn Pandey', 'Prashant Malvia',
  'Mohammad Asif Umar Ansari', 'Ankitkumar Virendra Yadav', 'Bilal Ahmad',
  'Shivkumar Jamuna Prasad Pandey', 'Yadav Ajeet Samarjeet',
  'Jabir Balu Devrukhakar', 'Vikas Billukumar Chandalliya',
  'Vinit Rakesh Singh', 'Vishal Sharma', 'Akshay Ankush Shinde',
  'Tushar Maruti Dadas', 'Akshay Subhash Tidake', 'Ashutosh Dilip Patil',
  'Prashant Keshav Nanavare', 'Sachin Kshirsagar',
  'Shaikh Rahim Shaikh Sharif', 'Sanved Bhausaheb Pagar',
  'Shaikh Altamash Shaikh Ismail', 'Brahmbhatt Dharmik',
  'Sourabh Badrinarayan Dubey', 'Anil Kumar Tusawra', 'Jayesh Trivedi',
  'Pipaliya Pratikkumar Popatbhai', 'Variya Milan Mukeshbhai',
  'Rajankumar Shantilal Hirpara', 'Ajaypal Singh Rajput', 'Srajal Laad',
  'Govind Patel', 'Harendra Sharma', 'Mohit Singh Mewada', 'Akash Dahariya',
  'Daymand', 'Jitesh Bagree', 'Tushar Dilip Mehar',
  'Vishwajit Eknath Thakare', 'Vicky Pramod Sahu', 'Soumen Biswas',
  'Ankush Pahari', 'Kartick Mondal', 'Suman Sen', 'Sayantan Ghosh',
  'Ranajit Singh', 'Sourav Roy', 'Manoj Bhuiya', 'Vacant',
  'Debanik Khatua', 'Vacant', 'Md Asrafuzzaman', 'Subhadip Bose',
  'Dipanjan Koner', 'Kalyan Gorai', 'Nadim Aktar', 'Utpal Rajbongshi',
  'Vickey Singh', 'Piyush Pratim Dutta', 'Bibhash Saha', 'Monoj Paul',
  'Angom Gunindro Singh', 'Ganpati Kumar', 'Sharma Vishwajeet Kumar',
  'Sunny Kumar', 'Suman Saurabh', 'Rohit Kumar Singh', 'Manoj Kumar',
  'Indrajeet Kumar Singh', 'Himanshu Panday', 'Soumendra Barik',
  'Prasanta Kumar Rout', 'Harihar Sahoo', 'Rama Krushna Nayak',
  'Ritik Kumar', 'Mandeep', 'Aniket Kumar', 'Amresh Singh', 'Hemant Batra',
  'Divyansh Bhardwaj', 'Ankur Sharma', 'Divyanshu Bajpai', 'Mohit Giri',
  'Mukesh Kumar', 'Adarsh Sanjay Dubey', 'Vishal Jaiswal',
  'Prabhat Kumar Singh', 'Shiv Kumar Kashyap', 'Tarun Srivastava',
  'Priyanshu Singh', 'Sagar Gupta', 'Akhandesh Ojha',
  'Yogesh Kumar Srivastava', 'Manoj Singh Bisht', 'Gaurav Chand',
  'Boby Rathaur', 'Rohit Sharma', 'Pradeep Kumar Dhakad', 'Nihal Sisodiya',
  'Rajesh Purohit', 'Madan Lal Bhoi', 'Lalit Mohan Chaturvedi',
  'Kartic Joshi', 'Harish Kumar', 'Parwez Alam', 'Rahul Malik',
  'Jasleen Singh', 'Manish Gupta', 'Aniket Sharma', 'Dawood Shafi Khan',
  'Aatish Seth', 'Pruthviraju L', 'Abhishek R', 'Mallikarjun Ishvarppa Mali',
  'Muttaraja G K', 'Santhosh Naik', 'Basavaraj Shivanand Madappanavar',
  'Basavaraj R', 'Ponmudi R', 'Prakash .', 'Karthik Jayakumar',
  'Narasingaperumal', 'Thangamani Dhandapani', 'Abish Ahamed S',
  'Mohammed Roshan A', 'Praveen Chandramani', 'Ganesan V.',
  'Sathishkumar S M', 'Aarif N', 'Arjun P', 'Akhil Raj R',
  'Abhijith Sabu', 'Afsal K A', 'Shijin Sam Jacob', 'Shijildas S',
  'Aneesh P', 'B Tirumalesh', 'Rajendhar Mamidipelly', 'Peddi Harishankar',
  'Batthula Sravan Kumar', 'Sangam Swamy Yadav', 'Ungarala Sri Shanmukha',
  'Nadipudi Durga Ganesh', 'Pappala Syam',
];

export const BRANDS = [
  'Ripatec & Lifanta',
  'Brivex & Optidew',
  'Tovaxo & Optidew',
  'Bidin LS & Hyane',
];
